import json

categories = [
    {
        "name": "Setup & DevOps",
        "label": "setup",
        "tasks": [
            "Configure root npm workspaces and turbo.json for monorepo orchestration",
            "Add .gitignore, .env.example, and README with project and architecture overview",
            "Create Docker Compose development stack with Postgres, backend, and frontend",
            "Add repository folder structure docs in docs/architecture.md",
            "Add package-level TypeScript configs for apps and shared packages",
            "Configure linting rules for TypeScript and Next/Nest code",
            "Add a workspace-level build script that runs app/package builds in parallel",
            "Create a local bootstrap script for environment setup and package install",
            "Add a GitHub Actions workflow skeleton for monorepo CI",
            "Create infra/scripts/deploy.sh scaffold for future deployment automation",
            "Add environment variable conventions and secret management docs",
            "Add local database seeding examples for PostgreSQL dev environment",
            "Document developer setup steps in README and docs/product-requirements.md",
            "Add shell script to validate node_modules and workspace symlinks",
            "Create a root-level npm script for running all package tests",
            "Add error handling conventions and logging guidelines to docs",
            "Document package publishing and versioning strategy for shared packages",
            "Create GitHub labels and issue templates docs for the backlog",
            "Add `.env` file example with Stellar network and API endpoints",
            "Add a CI check to validate package manifest versions and license fields",
            "Configure a consistent prettier configuration across the repo",
            "Create a cromwell-style service naming scheme for Docker resources",
            "Add a root-level `npm run clean` script to delete build artifacts",
            "Document branch naming conventions and pull request requirements",
            "Add a `docs/issue-backlog.md` summary for the generated issue list",
            "Add a review checklist for PRs that touch smart contract or wallet logic",
            "Add a local development startup guide for new contributors",
            "Add a pipeline step that verifies the contracts build in CI",
            "Create a test strategy section in docs/testing.md",
            "Add a monorepo dependency update policy document"
        ]
    },
    {
        "name": "Authentication & Users",
        "label": "auth",
        "tasks": [
            "Design the user entity model with reputation, wallet address, and roles",
            "Implement backend user registration endpoint with validation",
            "Implement backend login endpoint that returns JWT tokens",
            "Add route to fetch authenticated user profile in backend",
            "Add a user profile page in frontend dashboard",
            "Persist basic user metadata to PostgreSQL in backend",
            "Add user role support for maintainer and contributor types",
            "Add server-side middleware to validate JWT on protected routes",
            "Add a React hook for authenticated user context in frontend",
            "Add logout flow and token cleanup in frontend",
            "Add user avatar and profile details editing in frontend",
            "Add backend validation for wallet address format",
            "Add a route for linking Freighter wallet to a user account",
            "Add password reset and email recovery scaffolding in backend",
            "Implement frontend forms for registration and login",
            "Add acceptance error messages for registration failures",
            "Add user settings page with notification preferences",
            "Add backend support for disabling or banning a user",
            "Add activity timestamps to user profile records",
            "Add backend logging for user authentication events",
            "Add audit logs for user role changes",
            "Add endpoint to list users for admin maintenance",
            "Add tests for user registration and login endpoints",
            "Add a GraphQL or type-safe API contract for user objects",
            "Add frontend route guards to protect dashboard pages",
            "Add server-side user session refresh endpoint",
            "Add support for storing user GitHub profile links",
            "Document auth and user API in docs/api-spec.md",
            "Add feature flag support for future auth providers",
            "Add password complexity checks in backend"
        ]
    },
    {
        "name": "Wallet Integration",
        "label": "wallet",
        "tasks": [
            "Implement Freighter wallet detection in the frontend SDK",
            "Add a wallet connect button and modal to the homepage",
            "Implement wallet connection state management in frontend",
            "Add error handling for missing Freighter wallet installation",
            "Add support for switching between Stellar public and testnet networks",
            "Persist wallet public key in frontend session state only",
            "Add backend endpoint to verify wallet ownership via challenge signature",
            "Add frontend flow for signing an authentication challenge",
            "Document Freighter integration flow in docs/architecture.md",
            "Add transaction signing helper in packages/sdk for Soroban ops",
            "Add unit tests for wallet utilities in packages/sdk",
            "Add frontend UI to show connected wallet address and network",
            "Add disconnect wallet action and reset local state",
            "Add wallet connection experience on bounty creation screen",
            "Add backend validation for wallet-based user identity association",
            "Add support for sending signed transactions from frontend to backend",
            "Add error messaging for invalid or expired wallet signatures",
            "Add frontend loading state while Freighter approves requests",
            "Add integration test for wallet connect + submission flow",
            "Add fallback messaging for unsupported browser environments",
            "Add UI state for pending transaction signature requests",
            "Add a wallet audit event log in backend for connect/disconnect",
            "Add support for wallet refresh after session timeout",
            "Add retry strategy for Freighter connection failures",
            "Add wallet permissions docs for contributors and creators",
            "Add wallet connection analytics event naming strategy",
            "Add a wallet health-check endpoint in backend",
            "Add separate wallet connect flow for maintainer and contributor roles",
            "Add a secure storage policy for wallet account mapping in backend",
            "Add feature gating for Freighter-only wallet interactions"
        ]
    },
    {
        "name": "Smart Contracts (Escrow + payouts)",
        "label": "smart-contracts",
        "tasks": [
            "Design Soroban escrow contract storage schema for owner, amount, and state",
            "Implement contract initialization logic with owner and deposit amount",
            "Implement contract funding logic to lock bounty payment",
            "Implement payout release function to transfer funds to contributor",
            "Implement refund function for cancelled or expired bounties",
            "Add contract state enum for open, funded, completed, and refunded",
            "Add contract validation to prevent unauthorized payout execution",
            "Add gas-estimation utilities for contract transaction planning",
            "Add contract unit tests using Soroban test harness",
            "Add contract integration test for escrow lifecycle on testnet",
            "Add deployment script for Soroban contract to testnet",
            "Add contract ABI export for frontend SDK integration",
            "Add event logging for funding, approval, and payout actions",
            "Add dispute resolution stub to support future DAO review",
            "Add contract self-checks for amount consistency and owner match",
            "Add contract interface docs in docs/architecture.md",
            "Add backend contract orchestration service in packages/sdk",
            "Add contract error classification and retry behavior",
            "Add support for multi-asset payouts in contract logic",
            "Add tests for refund flow after bounty cancellation",
            "Add contract upgradeability strategy notes in docs",
            "Add contract interaction sample code in packages/sdk",
            "Add contract deployment verification endpoint in backend",
            "Add contract input validation for reward amount and deadline",
            "Add contract helper to fetch stored escrow metadata",
            "Add on-chain contract versioning metadata",
            "Add function to update bounty state after payout completion",
            "Add audit logs for contract calls through backend services",
            "Add support for contract status polling in frontend",
            "Add contract guard for zero-value funding transactions"
        ]
    },
    {
        "name": "Backend API",
        "label": "backend",
        "tasks": [
            "Create REST API route to list open bounties with pagination",
            "Create REST API route to retrieve bounty details by ID",
            "Create REST API route to create a new bounty with validation",
            "Create REST API route to update bounty metadata for owners",
            "Create REST API route to delete or cancel a bounty",
            "Create REST API route to submit work for a bounty",
            "Create REST API route to approve a submission and trigger payout",
            "Create REST API route to reject a submission with feedback",
            "Create REST API route to list submissions per user and bounty",
            "Add user profile endpoints for maintainer and contributor dashboards",
            "Add payment route to fund escrow contract with backend orchestration",
            "Add payment route to release funds after submission approval",
            "Add backend authorization guards for maintainer-only actions",
            "Add request validation for all API payloads",
            "Add error handling middleware for consistent API responses",
            "Add logging middleware for request traces and contract calls",
            "Add health-check route to verify database and Stellar connectivity",
            "Add backend metrics endpoint for API usage monitoring",
            "Add service layer for bounty business logic and status transitions",
            "Add repository layer for PostgreSQL persistence",
            "Add database schema migration docs and examples",
            "Add input sanitization for markdown or rich text fields",
            "Add rate limiting stub for API endpoints in backend",
            "Add endpoint to retrieve user activity and earnings summary",
            "Add support for bounty category query filters",
            "Add search endpoint for bounty title and description text",
            "Add endpoint to fetch contract funding status for a bounty",
            "Add backend test fixtures for API integration tests",
            "Add postman or OpenAPI export example for docs",
            "Document backend API routes in docs/api-spec.md"
        ]
    },
    {
        "name": "Frontend UI/UX",
        "label": "frontend",
        "tasks": [
            "Create homepage layout with featured bounties and platform messaging",
            "Create dashboard page for maintainers to manage bounties",
            "Create dashboard page for contributors to view submissions and earnings",
            "Create bounty creation wizard with title, amount, deadline, and requirements",
            "Create bounty detail page with payout status and submission list",
            "Create submission form with link field and GitHub PR reference",
            "Add wallet connect CTA and status indicator in header",
            "Add responsive navigation for desktop and mobile screens",
            "Add component for bounty cards with reward and deadline info",
            "Add UI for authorizing contract funding via Freighter",
            "Add maintainers view for reviewing and approving submissions",
            "Add contributor flow for tracking submission status",
            "Add in-app banner for wallet connection errors",
            "Add filter controls for categories, reward size, and status",
            "Add loader and skeleton states for page transitions",
            "Add error screens for missing bounty or submission not found",
            "Add personal dashboard stats for created and completed bounties",
            "Add contributor earnings history and payout summary card",
            "Add UI for user profile editing and wallet settings",
            "Add onboarding hints for first-time Freighter users",
            "Add contract funding status badge on bounty pages",
            "Add ability to copy wallet and bounty links to clipboard",
            "Add modal dialog for transaction confirmation steps",
            "Add support section for help articles and docs links",
            "Add accessibility support for keyboard navigation",
            "Add dark mode-friendly styling and color palette",
            "Add CTA for linking GitHub PRs on submission creation",
            "Add error handling UI for backend API failures",
            "Add toast notifications for successful bounty actions",
            "Document frontend page routes and component structure"
        ]
    },
    {
        "name": "Bounty & Submission Logic",
        "label": "bounties",
        "tasks": [
            "Define bounty lifecycle states and transitions in backend logic",
            "Implement status changes from open to funded after escrow funding",
            "Implement submission state transitions from pending to approved",
            "Implement reward escrow funding flow that records on contract and DB",
            "Implement deadline enforcement for bounty submissions",
            "Implement cancellation behavior for inactive or expired bounties",
            "Implement contributor assignment and notification stub",
            "Implement GitHub PR link validation on submission payloads",
            "Implement bounty category tags and requirements checklist",
            "Implement bounty search and filter behavior in backend",
            "Implement duplicate bounty detection or prevention guidance",
            "Implement submission acceptance criteria metadata in backend",
            "Implement partial milestones placeholder in bounty model",
            "Implement work submission history and audit trail",
            "Implement payout amount calculation and fee handling notes",
            "Implement bounty visibility settings for public/private listings",
            "Implement backend support for bounty attachments or URL references",
            "Implement validation that reward amount is positive and funded",
            "Implement automatic expiry cleanup for stale bounties",
            "Implement backend guard to prevent funding after approval",
            "Implement contract state synchronization after payout events",
            "Implement averting duplicate submissions by same contributor",
            "Implement bounty review notes for maintainers",
            "Implement approval flow that verifies contract payout details",
            "Implement confirmation step before on-chain payout execution",
            "Implement submission rejection reasons and contributor feedback",
            "Implement bounty headline and short description validation",
            "Implement backend tests for bounty state transitions",
            "Implement frontend validation for submission link formats",
            "Document bounty lifecycle in docs/bounty-flow.md"
        ]
    },
    {
        "name": "Notifications",
        "label": "notifications",
        "tasks": [
            "Design notification event types for bounty funding and approval",
            "Implement backend webhook endpoint for external notifications",
            "Implement email notification stub for user signup and updates",
            "Implement in-app notification store for frontend UI",
            "Implement a notifications list page in frontend dashboard",
            "Implement notification preference flags on user profile",
            "Implement backend service to queue notification events",
            "Implement notification generation for new submission alerts",
            "Implement notification generation for approved payouts",
            "Implement notification generation for bounty deadline reminders",
            "Implement backend logging for notification delivery attempts",
            "Implement retry handling for failed webhook deliveries",
            "Implement a notification badge for unread messages in UI",
            "Implement email templates for bounty and payout updates",
            "Implement backend API to mark notifications as read",
            "Implement notification filtering by type in frontend",
            "Implement support for webhook URL registration by project maintainers",
            "Implement user notification consent and opt-out controls",
            "Implement batching strategy for digest notifications",
            "Implement contract event hooks to trigger payout notifications",
            "Implement backend tests for notification payload formats",
            "Implement frontend toast messages for wallet and transaction events",
            "Implement docs for webhook payload schema in docs/api-spec.md",
            "Implement email delivery integration notes for SendGrid/Postmark",
            "Implement webhook security verification using HMAC signature",
            "Implement frontend notification preferences UI controls",
            "Implement notification persistence in PostgreSQL model",
            "Implement support for notifications on reputation changes",
            "Implement alerts for new GitHub PR submissions",
            "Implement fallback behavior when email service is unavailable"
        ]
    },
    {
        "name": "Reputation System",
        "label": "reputation",
        "tasks": [
            "Design reputation score model for contributors and maintainers",
            "Implement reputation changes after successful bounty completion",
            "Implement reputation deduction for rejected submissions",
            "Implement backend persistence of reputation history records",
            "Implement contributor rating input after payment release",
            "Implement maintainer rating input after submission approval",
            "Implement reputation dashboard card in frontend profile",
            "Implement reputation badge tiers for contributor status",
            "Implement backend guard to prevent abusive rating updates",
            "Implement reputation aggregation for leaderboard support",
            "Implement backend endpoint to fetch user reputation details",
            "Implement frontend display of contributor stars and trust score",
            "Implement fraud detection rules for repeated negative feedback",
            "Implement reputation-based filter for high-trust maintainers",
            "Implement backend service to recalculate reputation scores",
            "Implement reputation badge earned notifications",
            "Implement reputation update when user account is suspended",
            "Implement cheap reputation fallback for new contributors",
            "Implement trust score display on bounty listings",
            "Implement reputation history timeline in profile page",
            "Implement backend tests for reputation delta calculations",
            "Implement frontend UI for submitting review comments",
            "Implement support for DAO-based reputation voting stub",
            "Implement reputation impact docs in docs/product-requirements.md",
            "Implement recovery path for disputed reputation changes",
            "Implement contribution streak metrics for reputation bonuses",
            "Implement reputation penalties for contract dispute losses",
            "Implement frontend warning when reputation falls below threshold",
            "Implement schema migration to add reputation fields in database",
            "Implement admin endpoint to adjust reputation manually"
        ]
    },
    {
        "name": "Testing",
        "label": "testing",
        "tasks": [
            "Add unit test setup for backend NestJS services",
            "Add frontend component test setup for Next.js pages",
            "Add Soroban contract unit tests for escrow logic",
            "Add integration tests for backend API routes",
            "Add end-to-end test plan for wallet connect workflow",
            "Add contract deployment test against Soroban testnet simulator",
            "Add CI step to run lint, build, and tests for every PR",
            "Add test fixtures for user, bounty, and submission records",
            "Add test coverage reports for backend and frontend packages",
            "Add mock Freighter provider for wallet integration tests",
            "Add database migration tests for schema updates",
            "Add contract guard tests for invalid payout attempts",
            "Add performance smoke test for API list endpoints",
            "Add regression tests for bounty lifecycle status changes",
            "Add accessibility tests for core frontend pages",
            "Add API contract tests for response shapes and error codes",
            "Add mock notifications tests for backend event generation",
            "Add test harness for package shared utility functions",
            "Add frontend snapshot tests for UI component library",
            "Add doc tests for API examples in docs/api-spec.md",
            "Add local test runner commands in package scripts",
            "Add security test checklist for wallet and auth flows",
            "Add manual testing guide to docs/testing.md",
            "Add test harness for PostgreSQL integration with backend",
            "Add contract gas estimation regression test",
            "Add tests for multi-role authorization behavior",
            "Add CI gating to block merge on failing tests",
            "Add test coverage baseline for initial MVP features",
            "Add documentation of supported test commands in README",
            "Add database migration and seed generation tests for backend persistence"
        ]
    }
]

priority_cycle = ["High", "Medium", "Low"]

issues = []
for category in categories:
    for idx, task in enumerate(category["tasks"]):
        title = f"{category['name']}: {task}"
        description = (
            f"Implement the following {category['name']} task:\n\n"
            f"- {task}\n\n"
            f"This work should be implemented in the relevant app or package and documented in the repo."
        )
        acceptance = [
            f"The task is implemented in the appropriate files under the monorepo.",
            f"Automated tests or documentation are added where applicable.",
            "Code builds successfully and passes the configured linting rules."
        ]
        issue = {
            "title": title,
            "description": description,
            "acceptanceCriteria": acceptance,
            "labels": [category["label"], "MVP"],
            "priority": priority_cycle[idx % len(priority_cycle)],
            "estimate": "2d"
        }
        issues.append(issue)

with open("issues/stellar_bounty_300_issues.json", "w", encoding="utf-8") as f:
    json.dump(issues, f, indent=2)

print(f"Generated {len(issues)} issues.")
